services:
  next:
    container_name: cm_fb--frontend
    build:
      context: ./next
      dockerfile: Dockerfile.prod
    ports:
      - "7750:3000"
    networks:
      - cm_fb_network

  fastapi:
    container_name: cm_fb--backend
    build:
      context: ./fastapi
      dockerfile: Dockerfile.prod
    ports:
      - "7751:8000"
    networks:
      - cm_fb_network
    environment:
      PYTHONPATH: /app

networks:
  cm_fb_network:
    external: true