services:
  next:
    container_name: cm_fb--frontend
    build:
      context: ./next
      dockerfile: Dockerfile.dev
    ports:
      - "7750:3000"
    volumes:
      - ./next:/app
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    networks:
      - cm_fb--network

  fastapi:
    container_name: cm_fb--backend
    volumes:
      - ./fastapi/api:/app
    build:
      context: ./fastapi
      dockerfile: Dockerfile.dev
    ports:
      - "7751:8080"
    restart: always  # 自動再起動の設定
    networks:
      - cm_fb--network
    environment:
      PYTHONPATH: /app

volumes:
  node_modules:

networks:
  cm_fb--network:
    external: true